version: '3.7'

services: 
  service-up-meetup-clone:
      build: 
        context: . # The path of the Dockerfile
      environment: 
          SERVICE_NAME: meet-up-api
          DB_CONNECTION: pgsql
          DB_DRIVER: pgsql
          DB_HOST: up_db
          DB_PORT: 5433
      ports: 
          - 9000:8080
      networks: 
          - my-network
      depends_on: 
          - service-postgres
  service-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: meet_up
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./storage/db-data:/var/lib/postgresql/data"
    networks:
      - my-network
networks: 
    my-network:
      driver: bridge
